apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cpaas.io/creator: xiegm@allinpay.com
    cpaas.io/updated-at: '2022-05-17T06:25:15Z'
    deployment.kubernetes.io/revision: '3'
  creationTimestamp: '2022-05-17T05:51:46Z'
  generation: 6
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector:
            f:matchLabels:
              .: {}
              f:project.cpaas.io/name: {}
              f:service.cpaas.io/name: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:project.cpaas.io/name: {}
                f:service.cpaas.io/name: {}
            f:spec:
              f:containers:
                k:{"name":"istio-dubbo-grpc-service"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":8088,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:hostPort: {}
                      f:protocol: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: Mozilla
      operation: Update
      time: '2022-05-17T05:51:46Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:metadata:
              f:labels:
                f:app: {}
      manager: manager
      operation: Update
      time: '2022-05-17T05:56:13Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      time: '2022-05-17T06:25:20Z'
  name: istio-dubbo-grpc-service
  namespace: sft-test-flomesh
  resourceVersion: '83271283'
  selfLink: >-
    /apis/apps/v1/namespaces/sft-test-flomesh/deployments/istio-dubbo-grpc-service
  uid: 0557abd0-0895-47e5-90d7-f385c7ace81f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      project.cpaas.io/name: sft-test
      service.cpaas.io/name: deployment-istio-dubbo-grpc-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cpaas.io/creator: xiegm@allinpay.com
      creationTimestamp: null
      labels:
        app: istio-dubbo-grpc-service
        project.cpaas.io/name: sft-test
        service.cpaas.io/name: deployment-istio-dubbo-grpc-service
    spec:
      containers:
        - image: harbor02.sjzx.com/sftdev/istio-dubbo-grpc-service:2022041502
          imagePullPolicy: IfNotPresent
          name: istio-dubbo-grpc-service
          ports:
            - containerPort: 8088
              hostPort: 8088
              protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 4Gi
            requests:
              cpu: '4'
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2022-05-17T05:51:46Z'
      lastUpdateTime: '2022-05-17T05:51:46Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2022-05-17T05:51:46Z'
      lastUpdateTime: '2022-05-17T06:01:27Z'
      message: >-
        ReplicaSet "istio-dubbo-grpc-service-6bd74c5596" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
